//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoResidencias
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Area()
        {
            this.Estudiante = new HashSet<Estudiante>();
        }
    
        public int ID_Area { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<int> ID_Departamento { get; set; }
        public Nullable<int> ID_Puerta { get; set; }
        public Nullable<int> ID_Asesor { get; set; }
        public Nullable<int> ID_Jefe_Area { get; set; }
    
        public virtual Asesor_Tecnico Asesor_Tecnico { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual Jefe_Area Jefe_Area { get; set; }
        public virtual Puerta Puerta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estudiante> Estudiante { get; set; }
    }
}
