//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoResidencias
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Avance()
        {
            this.Programa = new HashSet<Programa>();
            this.Reportes = new HashSet<Reportes>();
        }
    
        public int ID_Avance { get; set; }
        public string Nota { get; set; }
        public int Avance_General { get; set; }
        public bool Peticion_folio_aceptacion { get; set; }
        public Nullable<System.DateTime> Fecha_Peticion_Folio_Aceptacion { get; set; }
        public byte Curso_De_Induccion { get; set; }
        public Nullable<System.DateTime> Fecha_Curso_Induccion { get; set; }
        public byte Peticion_Credencial { get; set; }
        public Nullable<System.DateTime> Fecha_Peticion_Credencial { get; set; }
        public Nullable<System.DateTime> Fecha_Llegada_Credencial { get; set; }
        public bool Credencial { get; set; }
        public Nullable<System.DateTime> Fecha_Credencial { get; set; }
        public Nullable<int> ID_Credencial { get; set; }
        public byte Peticion_Carta_Aceptacion { get; set; }
        public Nullable<System.DateTime> Fecha_Peticion_Carta_Aceptacion { get; set; }
        public Nullable<System.DateTime> Fecha_Llegada_Carta_Aceptacion { get; set; }
        public bool Carta_Aceptacion { get; set; }
        public Nullable<System.DateTime> Fecha_Carta_Aceptacion { get; set; }
        public Nullable<int> ID_Aceptacion { get; set; }
        public bool Carta_Terminacion_Area { get; set; }
        public Nullable<System.DateTime> Fecha_Carta_Terminacion_Area { get; set; }
        public bool Peticion_Folio_Carta_Terminacion { get; set; }
        public Nullable<System.DateTime> Fecha_Peticion_Folio_Carta_Terminacion { get; set; }
        public byte Peticion_Carta_Terminacion { get; set; }
        public Nullable<System.DateTime> Fecha_Peticion_Carta_Terminacion { get; set; }
        public Nullable<System.DateTime> Fecha_Llegada_Carta_Terminacion { get; set; }
        public bool Carta_Terminacion { get; set; }
        public Nullable<System.DateTime> Fecha_Carta_Terminacion { get; set; }
        public Nullable<int> ID_Terminacion { get; set; }
        public bool Estado { get; set; }
        public Nullable<System.DateTime> Fecha_Baja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Programa> Programa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reportes> Reportes { get; set; }
    }
}
