//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoResidencias
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datos_Escolares
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Datos_Escolares()
        {
            this.Estudiante = new HashSet<Estudiante>();
        }
    
        public int ID_Datos_Escolares { get; set; }
        public string Semestre { get; set; }
        public string Matricula { get; set; }
        public decimal Promedio_General { get; set; }
        public int ID_Escuela { get; set; }
        public int ID_Persona_Enc { get; set; }
        public int ID_Carrera { get; set; }
    
        public virtual Carrera Carrera { get; set; }
        public virtual Escuela Escuela { get; set; }
        public virtual Encargado_Escuela Encargado_Escuela { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estudiante> Estudiante { get; set; }
    }
}
