//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoResidencias
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante
    {
        public int ID_Estudiante { get; set; }
        public int ID_Datos_Personales { get; set; }
        public int ID_Datos_Escolares { get; set; }
        public int ID_Area { get; set; }
        public int ID_Expediente { get; set; }
        public int ID_Programa { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Datos_Escolares Datos_Escolares { get; set; }
        public virtual Datos_Personales Datos_Personales { get; set; }
        public virtual Expediente Expediente { get; set; }
        public virtual Programa Programa { get; set; }
    }
}
