//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoResidencias
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jefe_Area
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jefe_Area()
        {
            this.Area = new HashSet<Area>();
        }
    
        public int ID_Jefe_Area { get; set; }
        public string Nombre1_Jefe { get; set; }
        public string Nombre2_Jefe { get; set; }
        public string Apellido_Paterno_Jefe { get; set; }
        public string Apellido_Materno_Jefe { get; set; }
        public string Ficha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Area> Area { get; set; }
    }
}
