//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoResidencias
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisitos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requisitos()
        {
            this.Expediente = new HashSet<Expediente>();
        }
    
        public int ID_Requisitos { get; set; }
        public bool Carta_Presentacion { get; set; }
        public bool Carta_Seguro { get; set; }
        public bool Historial_Academico { get; set; }
        public bool Fotos { get; set; }
        public bool Comprobante_Domicilio { get; set; }
        public bool Acta_Nacimiento { get; set; }
        public bool Curp { get; set; }
        public bool Credencial_Escolar { get; set; }
        public bool Credencial_Elector { get; set; }
        public bool Carta_Compromiso { get; set; }
        public bool Cartilla_Servicio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expediente> Expediente { get; set; }
    }
}
