//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoResidencias
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tutor()
        {
            this.Datos_Personales = new HashSet<Datos_Personales>();
        }
    
        public int ID_Ref { get; set; }
        public string Nombre1_Tutor { get; set; }
        public string Nombre2_Tutor { get; set; }
        public string Ap_P_T { get; set; }
        public string AP_M_T { get; set; }
        public string TelefonoT { get; set; }
        public string Nombre1_Ref { get; set; }
        public string Nombre2_Ref { get; set; }
        public string AP_P_R { get; set; }
        public string AP_M_R { get; set; }
        public string TelefonoR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Datos_Personales> Datos_Personales { get; set; }
    }
}
